[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.26"
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
gas_limit = "9999999999999999"
fuzz = { runs = 10_000 }
invariant = { runs = 128, depth = 80 } 

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

